"""add sentiment_snapshots

Revision ID: 8c3404c1fe45
Revises: e139634d6d63
Create Date: 2026-05-02 20:10:48.605132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3404c1fe45'
down_revision: Union[str, Sequence[str], None] = 'e139634d6d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'ts', name='uq_sent_symbol_ts')
    )
    op.create_index('idx_sent_symbol_ts', 'sentiment_snapshots', ['symbol_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sent_symbol_ts', table_name='sentiment_snapshots')
    op.drop_table('sentiment_snapshots')
    # ### end Alembic commands ###
