"""add signal suggest+status columns

Revision ID: c8a63d8c4c9c
Revises: 8c3404c1fe45
Create Date: 2026-05-02 20:50:52.235178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a63d8c4c9c'
down_revision: Union[str, Sequence[str], None] = '8c3404c1fe45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
